In [1]:
import pandas as pd

In [2]:
df_orders = pd.read_csv('PappaOrdersCleaned.csv')
df_stock_info = pd.read_csv('CaseStocksSectors.csv')

In [3]:
df_orders.head()

,date,num_shares,company,ticker,price,foreign_commission,domestic_commission,order_type
0,2019-12-12,131500,Hanesbrands Inc.,HBI,15.197943,657.81,2997.80,buy
1,2019-12-12,39150,Charles Schwab,SCHW,51.083100,78.30,2999.83,buy
2,2019-12-12,20800,iShares Core MSCI EAFE ETF,IEFA,64.909500,41.60,2025.18,buy
3,2019-12-12,5200,iShares Core MSCI EAFE ETF,IEFA,64.916000,10.40,506.32,buy
4,2019-12-09,77300,iShares Core MSCI EAFE ETF,IEFA,64.441500,154.60,7472.02,buy

In [4]:
df_stock_info.head()

,ticker,Agriculture,Bulk shipping,China,Coal,Copper,Emerging Markets,Global,Gold,Natural gas,Natural resources,Nuclear,Oil drilling,Oil integrated,Oil rigs,Oil services,Precious Metals,Tankers,Oil,Energy
0,ADM,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,AEM,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,True,False,False,False
2,AMRK,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False
3,BABA,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
4,BTG,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,True,False,False,False

In [5]:
tickers = df_stock_info['ticker'].unique()
filtered_df_orders = df_orders[df_orders['ticker'].isin(tickers)]
filtered_df_orders.head()

,date,num_shares,company,ticker,price,foreign_commission,domestic_commission,order_type
5,2019-12-09,96500,iShares Core MSCI Emerging Markets ETF,IEMG,51.687663,482.54,7481.80,buy
7,2019-12-06,97000,iShares Core MSCI Emerging Markets ETF,IEMG,51.774173,485.02,7533.12,buy
11,2019-11-26,54000,Schlumberger Ltd.,SLB,36.504300,270.00,2956.81,buy
12,2019-11-25,97000,iShares Core MSCI Emerging Markets ETF,IEMG,51.984509,51.98,7563.71,buy
18,2019-11-25,82000,Schlumberger Ltd.,SLB,36.808100,410.00,4527.35,buy

In [9]:
filtered_df_orders.sort_values(by=['date'], inplace=True)
filtered_df_orders.to_csv('PappaOrdersFiltered.csv', index=False)

/var/folders/dy/mtplz5t11tv7w14rf5z7nx_r0000gn/T/ipykernel_41564/1546370567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df_orders.sort_values(by=['date'], inplace=True)

In [10]:
filtered_df_orders

,date,num_shares,company,ticker,price,foreign_commission,domestic_commission,order_type
12,2019-11-25,97000,iShares Core MSCI Emerging Markets ETF,IEMG,51.984509,51.98,7563.71,buy
18,2019-11-25,82000,Schlumberger Ltd.,SLB,36.808100,410.00,4527.35,buy
11,2019-11-26,54000,Schlumberger Ltd.,SLB,36.504300,270.00,2956.81,buy
7,2019-12-06,97000,iShares Core MSCI Emerging Markets ETF,IEMG,51.774173,485.02,7533.12,buy
5,2019-12-09,96500,iShares Core MSCI Emerging Markets ETF,IEMG,51.687663,482.54,7481.80,buy
...,...,...,...,...,...,...,...,...
333,2025-05-20,28000,Schlumberger,SLB,34.624736,140.37,1454.27,buy
336,2025-05-23,14000,A-Mark Precious Metals,AMRK,20.126836,70.00,421.90,buy
334,2025-05-23,85000,Glencore,GLNCY,7.248300,308.05,924.20,buy
335,2025-05-23,20000,Seabridge Gold,SA,12.225500,100.00,366.79,buy
337,2025-05-23,36000,Canadian Natural Resources,CNQ,30.928600,180.00,1670.17,buy

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date
def filter_orders_by_ticker(df_orders: pd.DataFrame, tickers: list[str]) -> pd.DataFrame:
    """
    Filters the orders DataFrame to include only the specified tickers.
    
    Parameters:
    df_orders (pd.DataFrame): DataFrame containing order data.
    tickers (list[str]): List of ticker symbols to filter by.
    
    Returns:
    pd.DataFrame: Filtered DataFrame containing only the specified tickers.
    """
    return df_orders[df_orders['ticker'].isin(tickers)]

def filter_orders_by_date(df_orders: pd.DataFrame, start_date: date, end_date: date) -> pd.DataFrame:
    """
    Filters the orders DataFrame to include only orders from a specified start date onwards.
    
    Parameters:
    df_orders (pd.DataFrame): DataFrame containing order data.
    start_date (date): The start date to filter orders from.
    
    Returns:
    pd.DataFrame: Filtered DataFrame containing orders from the specified start date onwards.
    """
    return df_orders[df_orders['date'] >= start_date & df_orders['date'] <= end_date]

def plot_tickers(df_orders: pd.DataFrame, tickers: list[str], start_date: date, end_date: date = None) -> pd.DataFrame:
    """
    """

    plt.figure(figsize=(14, 7))
    for ticker in tickers:
        ticker_data = df_orders[df_orders['ticker'] == ticker]
        sns.lineplot(data=ticker_data, x='date', y='price', label=ticker)

    plt.title('Stock Prices Over Time')
    plt.xlabel('Date')
    plt.ylabel('Price')
    plt.xticks(rotation=45)
    plt.legend()
    plt.tight_layout()
    plt.show()